version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: jensvercruysse/raspberrypi-cluster:pi
    deploy:
      replicas: 21
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.8"
          memory: 200M
    ports:
      - "80:80"
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/home/pi/data:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet
networks:
  webnet:
